title: <p align="center"> Nazneen Ansari </p>
logo: /assets/img/my_pic.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/nazneen-ansari">LinkedIn</a> |
  <a href="https://github.com/nazneenansari">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
  Working in AdTech domain for 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal